version: '3.8'

services:
  web:
    build: .
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_NAME: user040
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    command: sh -c "ssh -N -L 3307:sql.cs.usfca.edu:3306 mchanson3@stargate.cs.usfca.edu & python manage.py runserver 0.0.0.0:8000"


    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  db_data:
