# Generated by Django 4.2.5 on 2023-10-01 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demographic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager_application.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager_application.creator')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_count', models.IntegerField()),
                ('handle', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager_application.creator')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager_application.platform')),
            ],
            options={
                'unique_together': {('creator', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='CreatorDemographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager_application.creator')),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager_application.demographic')),
            ],
            options={
                'unique_together': {('creator', 'demographic')},
            },
        ),
    ]
